import Link from 'next/link';
import {
  Mic,
  Sparkles,
  FileText,
  CheckSquare,
  Scale,
  Search,
  Bot,
  Mail,
  ArrowRight,
  ShieldCheck,
  Zap,
} from 'lucide-react';

export default function LandingPage() {
  return (
    <div className="space-y-24 pb-20">
      {/* Hero Section */}
      <section className="relative pt-20 pb-16 px-4 sm:px-6 lg:px-8 max-w-7xl mx-auto text-center overflow-hidden">
        <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full glass-panel border border-indigo-500/30 text-indigo-300 text-xs font-semibold mb-8 animate-glow">
          <Sparkles className="w-4 h-4 text-indigo-400" />
          <span>Powered by openai/whisper-small & Open-Source LLMs</span>
        </div>

        <h1 className="text-4xl sm:text-6xl font-extrabold font-heading text-white tracking-tight leading-tight max-w-4xl mx-auto">
          Meeting Recording <span className="text-gradient">→ Transcription →</span> Actionable AI Insights
        </h1>

        <p className="mt-6 text-base sm:text-lg text-slate-400 max-w-2xl mx-auto leading-relaxed">
          Automatically convert recorded meeting audio & video into accurate timestamped transcripts, executive summaries, assignees for action items, key decisions, interactive AI Q&A, and follow-up email drafts.
        </p>

        <div className="mt-10 flex flex-wrap justify-center gap-4">
          <Link
            href="/upload"
            className="px-8 py-4 rounded-xl font-bold text-sm bg-gradient-to-r from-indigo-600 to-purple-600 text-white shadow-xl shadow-indigo-500/25 hover:scale-105 active:scale-95 transition-all flex items-center gap-2"
          >
            <Mic className="w-5 h-5" />
            Upload Meeting Recording
            <ArrowRight className="w-4 h-4" />
          </Link>
          <Link
            href="/dashboard"
            className="px-8 py-4 rounded-xl font-bold text-sm glass-panel border border-slate-700 text-slate-200 hover:bg-slate-800/80 transition-colors"
          >
            Explore Dashboard
          </Link>
        </div>
      </section>

      {/* MVP Features Grid */}
      <section className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="text-center mb-16">
          <h2 className="text-2xl sm:text-3xl font-extrabold font-heading text-white">
            Comprehensive Meeting Intelligence Features
          </h2>
          <p className="text-slate-400 text-sm mt-2">
            Everything your team needs to capture, search, and act on meeting outcomes.
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          <FeatureCard
            icon={<Mic className="w-6 h-6 text-indigo-400" />}
            title="🎙️ Upload Meeting Audio & Video"
            description="Upload MP3, WAV, M4A, MP4, and WebM files with drag-and-drop ease and real-time processing progress."
          />
          <FeatureCard
            icon={<FileText className="w-6 h-6 text-indigo-400" />}
            title="📝 Interactive Transcription"
            description="Whisper Small extracts timestamped speech segments synced directly to media playback controls."
          />
          <FeatureCard
            icon={<Sparkles className="w-6 h-6 text-purple-400" />}
            title="🤖 AI-Generated Summaries"
            description="Get executive summaries and key discussion points generated by open-source LLMs."
          />
          <FeatureCard
            icon={<CheckSquare className="w-6 h-6 text-emerald-400" />}
            title="✅ Action Items with Assignees"
            description="Automatically extract tasks, assign responsible persons and deadlines, with status toggles."
          />
          <FeatureCard
            icon={<Scale className="w-6 h-6 text-amber-400" />}
            title="📌 Important Decisions"
            description="Detect and highlight major organizational and project decisions made during meetings."
          />
          <FeatureCard
            icon={<Search className="w-6 h-6 text-cyan-400" />}
            title="🔎 Search Within Meetings"
            description="Instantly query transcripts, topics, and action items by keywords."
          />
          <FeatureCard
            icon={<Bot className="w-6 h-6 text-indigo-400" />}
            title="💬 Ask AI Questions"
            description="Interactive natural-language Q&A assistant to ask anything about specific meetings."
          />
          <FeatureCard
            icon={<Mail className="w-6 h-6 text-pink-400" />}
            title="✉️ Follow-Up Email Generator"
            description="Generate editable, professional follow-up email drafts with one-click clipboard copying."
          />
          <FeatureCard
            icon={<ShieldCheck className="w-6 h-6 text-emerald-400" />}
            title="🔒 Free & Open-Source Stack"
            description="Runs with zero expensive subscription lock-in using open-source models."
          />
        </div>
      </section>
    </div>
  );
}

function FeatureCard({
  icon,
  title,
  description,
}: {
  icon: React.ReactNode;
  title: string;
  description: string;
}) {
  return (
    <div className="glass-panel glass-panel-hover p-6 rounded-2xl border border-slate-800/80 flex flex-col justify-between">
      <div>
        <div className="p-3 rounded-xl bg-slate-900 border border-slate-800 inline-block mb-4">
          {icon}
        </div>
        <h3 className="text-base font-bold font-heading text-white mb-2">{title}</h3>
        <p className="text-xs text-slate-400 leading-relaxed">{description}</p>
      </div>
    </div>
  );
}
